export const PLAN_CODES = {
  FREE: 'FREE',
  STARTER: 'STARTER',
  PROFESSIONAL: 'PROFESSIONAL',
  ENTERPRISE: 'ENTERPRISE'
};

export const SUBSCRIPTION_STATUS = {
  TRIAL: 'TRIAL',
  ACTIVE: 'ACTIVE',
  PAST_DUE: 'PAST_DUE',
  CANCELED: 'CANCELED'
};

export const PAYMENT_PROVIDERS = {
  NONE: 'NONE',
  STRIPE: 'STRIPE',
  PAYPAL: 'PAYPAL',
  MOMO: 'MOMO',
  VNPAY: 'VNPAY'
};

export const BILLING_CYCLES = {
  MONTHLY: 'MONTHLY',
  YEARLY: 'YEARLY'
};